# Generated by Django 3.1 on 2020-10-01 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200928_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='users_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
