# Generated by Django 3.1 on 2020-10-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_follows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
    ]
